jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: cd src && pytest
          name: Test
orbs:
  python: circleci/python@0.3.2
version: 2.1
workflows:
  main:
    jobs:
      - test
